# @package __global__

# This is a minimal debugging configuration
# for MusicGen training solver
defaults:
  - musicgen/default
  - /model: lm/musicgen_lm
  - override /dset: audio/soundsauce_starter
  - _self_

autocast: true
autocast_dtype: float16
compression_model_checkpoint: //pretrained/facebook/encodec_32khz
transformer_lm:
  n_q: 4
  card: 2048

codebooks_pattern:
  modeling: parallel

channels: 1
sample_rate: 32000

deadlock:
  use: true  # deadlock detection

dataset:
  num_workers: 4
  batch_size: 32
  segment_duration: 12
  sample_on_weight: false  # Uniform sampling all the way
  sample_on_duration: false  # Uniform sampling all the way
  generate:
    num_samples: 8

generate:
  audio:
    strategy: peak
  lm:
    use_sampling: true
    top_k: 250
    top_p: 0.0
    gen_duration: 12
    prompted_samples: false

checkpoint:
  save_every: 10
  keep_last: 10

optim:
  epochs: 500
  optimizer: dadam
  lr: 1
  ema:
    use: true
    updates: 10
    device: cuda
  updates_per_epoch: 500

logging:
  log_wandb: true
wandb:
  project: audiocraft

schedule:
  lr_scheduler: cosine
  cosine:
    warmup: 4000
    lr_min_ratio: 0.0
    cycle_length: 1.0