# @package __global__

# This is a minimal debugging configuration
# for MusicGen training solver
defaults:
  - musicgen/default
  - /model: lm/musicgen_lm
  - override /model/lm/model_scale: xsmall
  - override /dset: audio/soundsauce_starter
  - _self_

autocast: false
compression_model_checkpoint: //pretrained/facebook/encodec_32khz
transformer_lm:
  n_q: 4
  card: 400

codebooks_pattern:
  modeling: parallel

channels: 1
sample_rate: 32000

deadlock:
  use: true  # deadlock detection

dataset:
  batch_size: 4
  segment_duration: 5
  sample_on_weight: false  # Uniform sampling all the way
  sample_on_duration: false  # Uniform sampling all the way

generate:
  audio:
    strategy: peak
  lm:
    use_sampling: false
    top_k: 0
    top_p: 0.0

checkpoint:
  save_every: 10
  keep_last: 10

optim:
  epochs: 500
  optimizer: dadam
  lr: 1
  ema:
    use: true
    updates: 10
    device: cuda

logging:
  log_tensorboard: true

schedule:
  lr_scheduler: cosine
  cosine:
    warmup: 4000
    lr_min_ratio: 0.0
    cycle_length: 1.0